# Deployment config for dashboards
config:
    vital-signs:
        layout: metrics-by-project
        config: VitalSigns
        piwikHost: piwik.wikimedia.org
        piwikId: 6
        hostname: vital-signs-test.wmflabs.org
        subfolder:

    edit-analysis:
        layout: compare
        config: VisualEditorAndWikitext
        piwikHost:
        piwikId:
        hostname: edit-analysis-test.wmflabs.org
        subfolder: compare

    language-reportcard:
        layout: metrics-by-project
        config: LanguageReportcard
        piwikHost:
        piwikId:
        hostname: language-reportcard-test.wmflabs.org
        subfolder:

    multimedia-health:
        layout: metrics-by-project
        config: MultimediaHealth
        piwikHost:
        piwikId:
        hostname: edit-analysis-test.wmflabs.org
        subfolder: multimedia-health

    flow-by-wiki:
        layout: metrics-by-project
        config: FlowByWiki
        piwikHost:
        piwikId:
        hostname: edit-analysis-test.wmflabs.org
        subfolder: beta-enables
